language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
#  - "pypy" is not currently supported
script:
  - python setup.py nosetests
  # test package creation and installation
  - python setup.py sdist --formats=zip
  - find ./dist -iname "*.zip" -print0 | xargs -0 pip install
  - python -c "import event"